# Generated by Django 4.2.23 on 2025-07-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_tag_options_tag_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='from_api',
            field=models.BooleanField(default=False, help_text='Создано через API'),
        ),
    ]
