# Generated by Django 4.2.23 on 2025-07-02 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_from_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Слаг может содержать только буквы, цифры, дефисы и знаки подчеркивания (включая кириллицу).', regex='^[-\\w\\u0400-\\u04FF]+$')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Слаг может содержать только буквы, цифры, дефисы и знаки подчеркивания (включая кириллицу).', regex='^[-\\w\\u0400-\\u04FF]+$')]),
        ),
    ]
