# Generated by Django 4.2.23 on 2025-07-06 13:43

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=news.models.news_cover_path),
        ),
    ]
