version: "3.9"

services:

  web:
    build:
      context: ./newsblog
    command: gunicorn newsblog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./newsblog:/app
      # Медиа файлы мапим на хост для nginx
      - ./newsblog/media:/app/media
      # Статические файлы мапим на хост для nginx
      - ./newsblog/staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
      - frontend/.env.local
    depends_on:
      - web

